(cl:defpackage action_client-msg
  (:use )
  (:export
   "<DEFACTION>"
   "DEFACTION"
   "<DEFACTIONFEEDBACK>"
   "DEFACTIONFEEDBACK"
   "<DEFACTIONGOAL>"
   "DEFACTIONGOAL"
   "<DEFACTIONRESULT>"
   "DEFACTIONRESULT"
   "<DEFFEEDBACK>"
   "DEFFEEDBACK"
   "<DEFGOAL>"
   "DEFGOAL"
   "<DEFRESULT>"
   "DEFRESULT"
  ))

