// Generated by gencpp from file object_detection/GoalPositions.msg
// DO NOT EDIT!


#ifndef OBJECT_DETECTION_MESSAGE_GOALPOSITIONS_H
#define OBJECT_DETECTION_MESSAGE_GOALPOSITIONS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <object_detection/GoalPos.h>

namespace object_detection
{
template <class ContainerAllocator>
struct GoalPositions_
{
  typedef GoalPositions_<ContainerAllocator> Type;

  GoalPositions_()
    : Coords()  {
    }
  GoalPositions_(const ContainerAllocator& _alloc)
    : Coords(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::object_detection::GoalPos_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::object_detection::GoalPos_<ContainerAllocator> >::other >  _Coords_type;
  _Coords_type Coords;





  typedef boost::shared_ptr< ::object_detection::GoalPositions_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_detection::GoalPositions_<ContainerAllocator> const> ConstPtr;

}; // struct GoalPositions_

typedef ::object_detection::GoalPositions_<std::allocator<void> > GoalPositions;

typedef boost::shared_ptr< ::object_detection::GoalPositions > GoalPositionsPtr;
typedef boost::shared_ptr< ::object_detection::GoalPositions const> GoalPositionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_detection::GoalPositions_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_detection::GoalPositions_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::object_detection::GoalPositions_<ContainerAllocator1> & lhs, const ::object_detection::GoalPositions_<ContainerAllocator2> & rhs)
{
  return lhs.Coords == rhs.Coords;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::object_detection::GoalPositions_<ContainerAllocator1> & lhs, const ::object_detection::GoalPositions_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace object_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::object_detection::GoalPositions_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detection::GoalPositions_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_detection::GoalPositions_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_detection::GoalPositions_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detection::GoalPositions_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detection::GoalPositions_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_detection::GoalPositions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e1cbfbf293ab70ab330ff223c5f1fcd";
  }

  static const char* value(const ::object_detection::GoalPositions_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e1cbfbf293ab70aULL;
  static const uint64_t static_value2 = 0xb330ff223c5f1fcdULL;
};

template<class ContainerAllocator>
struct DataType< ::object_detection::GoalPositions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_detection/GoalPositions";
  }

  static const char* value(const ::object_detection::GoalPositions_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_detection::GoalPositions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "GoalPos[] Coords\n"
"\n"
"================================================================================\n"
"MSG: object_detection/GoalPos\n"
"float32 X\n"
"float32 Y\n"
"float32 Z\n"
;
  }

  static const char* value(const ::object_detection::GoalPositions_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_detection::GoalPositions_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Coords);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoalPositions_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_detection::GoalPositions_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_detection::GoalPositions_<ContainerAllocator>& v)
  {
    s << indent << "Coords[]" << std::endl;
    for (size_t i = 0; i < v.Coords.size(); ++i)
    {
      s << indent << "  Coords[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::object_detection::GoalPos_<ContainerAllocator> >::stream(s, indent + "    ", v.Coords[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_DETECTION_MESSAGE_GOALPOSITIONS_H
