// Generated by gencpp from file object_detection/GoalPos.msg
// DO NOT EDIT!


#ifndef OBJECT_DETECTION_MESSAGE_GOALPOS_H
#define OBJECT_DETECTION_MESSAGE_GOALPOS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace object_detection
{
template <class ContainerAllocator>
struct GoalPos_
{
  typedef GoalPos_<ContainerAllocator> Type;

  GoalPos_()
    : X(0.0)
    , Y(0.0)
    , Z(0.0)  {
    }
  GoalPos_(const ContainerAllocator& _alloc)
    : X(0.0)
    , Y(0.0)
    , Z(0.0)  {
  (void)_alloc;
    }



   typedef float _X_type;
  _X_type X;

   typedef float _Y_type;
  _Y_type Y;

   typedef float _Z_type;
  _Z_type Z;





  typedef boost::shared_ptr< ::object_detection::GoalPos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_detection::GoalPos_<ContainerAllocator> const> ConstPtr;

}; // struct GoalPos_

typedef ::object_detection::GoalPos_<std::allocator<void> > GoalPos;

typedef boost::shared_ptr< ::object_detection::GoalPos > GoalPosPtr;
typedef boost::shared_ptr< ::object_detection::GoalPos const> GoalPosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_detection::GoalPos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_detection::GoalPos_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::object_detection::GoalPos_<ContainerAllocator1> & lhs, const ::object_detection::GoalPos_<ContainerAllocator2> & rhs)
{
  return lhs.X == rhs.X &&
    lhs.Y == rhs.Y &&
    lhs.Z == rhs.Z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::object_detection::GoalPos_<ContainerAllocator1> & lhs, const ::object_detection::GoalPos_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace object_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::object_detection::GoalPos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detection::GoalPos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_detection::GoalPos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_detection::GoalPos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detection::GoalPos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detection::GoalPos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_detection::GoalPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a1dfb8f61d81d8e9fe291bc0d86a2f48";
  }

  static const char* value(const ::object_detection::GoalPos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa1dfb8f61d81d8e9ULL;
  static const uint64_t static_value2 = 0xfe291bc0d86a2f48ULL;
};

template<class ContainerAllocator>
struct DataType< ::object_detection::GoalPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_detection/GoalPos";
  }

  static const char* value(const ::object_detection::GoalPos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_detection::GoalPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 X\n"
"float32 Y\n"
"float32 Z\n"
;
  }

  static const char* value(const ::object_detection::GoalPos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_detection::GoalPos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.X);
      stream.next(m.Y);
      stream.next(m.Z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoalPos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_detection::GoalPos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_detection::GoalPos_<ContainerAllocator>& v)
  {
    s << indent << "X: ";
    Printer<float>::stream(s, indent + "  ", v.X);
    s << indent << "Y: ";
    Printer<float>::stream(s, indent + "  ", v.Y);
    s << indent << "Z: ";
    Printer<float>::stream(s, indent + "  ", v.Z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_DETECTION_MESSAGE_GOALPOS_H
