// Generated by gencpp from file object_detection/Localization.msg
// DO NOT EDIT!


#ifndef OBJECT_DETECTION_MESSAGE_LOCALIZATION_H
#define OBJECT_DETECTION_MESSAGE_LOCALIZATION_H

#include <ros/service_traits.h>


#include <object_detection/LocalizationRequest.h>
#include <object_detection/LocalizationResponse.h>


namespace object_detection
{

struct Localization
{

typedef LocalizationRequest Request;
typedef LocalizationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Localization
} // namespace object_detection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::object_detection::Localization > {
  static const char* value()
  {
    return "742db672f1005567be304d1ccc310265";
  }

  static const char* value(const ::object_detection::Localization&) { return value(); }
};

template<>
struct DataType< ::object_detection::Localization > {
  static const char* value()
  {
    return "object_detection/Localization";
  }

  static const char* value(const ::object_detection::Localization&) { return value(); }
};


// service_traits::MD5Sum< ::object_detection::LocalizationRequest> should match
// service_traits::MD5Sum< ::object_detection::Localization >
template<>
struct MD5Sum< ::object_detection::LocalizationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::object_detection::Localization >::value();
  }
  static const char* value(const ::object_detection::LocalizationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_detection::LocalizationRequest> should match
// service_traits::DataType< ::object_detection::Localization >
template<>
struct DataType< ::object_detection::LocalizationRequest>
{
  static const char* value()
  {
    return DataType< ::object_detection::Localization >::value();
  }
  static const char* value(const ::object_detection::LocalizationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::object_detection::LocalizationResponse> should match
// service_traits::MD5Sum< ::object_detection::Localization >
template<>
struct MD5Sum< ::object_detection::LocalizationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::object_detection::Localization >::value();
  }
  static const char* value(const ::object_detection::LocalizationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_detection::LocalizationResponse> should match
// service_traits::DataType< ::object_detection::Localization >
template<>
struct DataType< ::object_detection::LocalizationResponse>
{
  static const char* value()
  {
    return DataType< ::object_detection::Localization >::value();
  }
  static const char* value(const ::object_detection::LocalizationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OBJECT_DETECTION_MESSAGE_LOCALIZATION_H
