; Auto-generated. Do not edit!


(cl:in-package safety_action_client-msg)


;//! \htmlinclude defFeedback.msg.html

(cl:defclass <defFeedback> (roslisp-msg-protocol:ros-message)
  ((distance
    :reader distance
    :initarg :distance
    :type cl:float
    :initform 0.0))
)

(cl:defclass defFeedback (<defFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <defFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'defFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name safety_action_client-msg:<defFeedback> is deprecated: use safety_action_client-msg:defFeedback instead.")))

(cl:ensure-generic-function 'distance-val :lambda-list '(m))
(cl:defmethod distance-val ((m <defFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader safety_action_client-msg:distance-val is deprecated.  Use safety_action_client-msg:distance instead.")
  (distance m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <defFeedback>) ostream)
  "Serializes a message object of type '<defFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'distance))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <defFeedback>) istream)
  "Deserializes a message object of type '<defFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'distance) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<defFeedback>)))
  "Returns string type for a message object of type '<defFeedback>"
  "safety_action_client/defFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'defFeedback)))
  "Returns string type for a message object of type 'defFeedback"
  "safety_action_client/defFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<defFeedback>)))
  "Returns md5sum for a message object of type '<defFeedback>"
  "acff7fda0c683c872875f5c4b069f124")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'defFeedback)))
  "Returns md5sum for a message object of type 'defFeedback"
  "acff7fda0c683c872875f5c4b069f124")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<defFeedback>)))
  "Returns full string definition for message of type '<defFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float64 distance~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'defFeedback)))
  "Returns full string definition for message of type 'defFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float64 distance~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <defFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <defFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'defFeedback
    (cl:cons ':distance (distance msg))
))
