// Generated by gencpp from file action_client/defResult.msg
// DO NOT EDIT!


#ifndef ACTION_CLIENT_MESSAGE_DEFRESULT_H
#define ACTION_CLIENT_MESSAGE_DEFRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace action_client
{
template <class ContainerAllocator>
struct defResult_
{
  typedef defResult_<ContainerAllocator> Type;

  defResult_()
    : status(false)  {
    }
  defResult_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::action_client::defResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_client::defResult_<ContainerAllocator> const> ConstPtr;

}; // struct defResult_

typedef ::action_client::defResult_<std::allocator<void> > defResult;

typedef boost::shared_ptr< ::action_client::defResult > defResultPtr;
typedef boost::shared_ptr< ::action_client::defResult const> defResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action_client::defResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action_client::defResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::action_client::defResult_<ContainerAllocator1> & lhs, const ::action_client::defResult_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::action_client::defResult_<ContainerAllocator1> & lhs, const ::action_client::defResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace action_client

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::action_client::defResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_client::defResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_client::defResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_client::defResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_client::defResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_client::defResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action_client::defResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::action_client::defResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::action_client::defResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action_client/defResult";
  }

  static const char* value(const ::action_client::defResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action_client::defResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result\n"
"bool status\n"
;
  }

  static const char* value(const ::action_client::defResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action_client::defResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct defResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_client::defResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::action_client::defResult_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_CLIENT_MESSAGE_DEFRESULT_H
