// Generated by gencpp from file action_server/defFeedback.msg
// DO NOT EDIT!


#ifndef ACTION_SERVER_MESSAGE_DEFFEEDBACK_H
#define ACTION_SERVER_MESSAGE_DEFFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace action_server
{
template <class ContainerAllocator>
struct defFeedback_
{
  typedef defFeedback_<ContainerAllocator> Type;

  defFeedback_()
    : distance(0.0)  {
    }
  defFeedback_(const ContainerAllocator& _alloc)
    : distance(0.0)  {
  (void)_alloc;
    }



   typedef double _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::action_server::defFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_server::defFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct defFeedback_

typedef ::action_server::defFeedback_<std::allocator<void> > defFeedback;

typedef boost::shared_ptr< ::action_server::defFeedback > defFeedbackPtr;
typedef boost::shared_ptr< ::action_server::defFeedback const> defFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action_server::defFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action_server::defFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::action_server::defFeedback_<ContainerAllocator1> & lhs, const ::action_server::defFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::action_server::defFeedback_<ContainerAllocator1> & lhs, const ::action_server::defFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace action_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::action_server::defFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_server::defFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_server::defFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_server::defFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_server::defFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_server::defFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action_server::defFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acff7fda0c683c872875f5c4b069f124";
  }

  static const char* value(const ::action_server::defFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xacff7fda0c683c87ULL;
  static const uint64_t static_value2 = 0x2875f5c4b069f124ULL;
};

template<class ContainerAllocator>
struct DataType< ::action_server::defFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action_server/defFeedback";
  }

  static const char* value(const ::action_server::defFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action_server::defFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"float64 distance\n"
"\n"
;
  }

  static const char* value(const ::action_server::defFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action_server::defFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct defFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_server::defFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::action_server::defFeedback_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_SERVER_MESSAGE_DEFFEEDBACK_H
